### ISSUE TITLE
Crash when trying to load OG Xbox games

### ISSUE THREAD

**Issue by Electric1447** [StelioKontosXBL/AuroraCrashPatcher#5]
When using the plugin, loading any og xbox games would load for a second turn to a black screen and crash to Aurora dashboard

AuroraCrashPatcher version: 1.2
Hardware: Jasper
XeBuild: Glitch2
Kernel: 17559

**Comment by Makein** [comment]
Do you dl all covers? No nag about crash dl?
Then disable AuroraCrashPatcher plugin and use your xbox360 as you do...

**Comment by Electric1447** [comment]
I did download all covers

**Comment by Ste1io** [comment]
That could be your stealth, or any other plugin for that matter, also. Typically when playing og games it's best to boot with no plugins (open the disc tray immediately after hitting the power button to boot up) to disable plugins that could interfere (as most do). Booting with tray open will disable AuroraCrashPatcher as well, and won't interfere with playing og games (already tested and verified). If you're having different results, load up the Debug version (from the "Dist" folder), and send me the log file it generates on your Hdd afterwards.

**Comment by Electric1447** [comment]
I have no other plugin/stealth servers.
Launching the games through XexMenu with the plugin installed does not crash the game.
So the problem lays in Aurora.

**Comment by Electric1447** [comment]
I'll send the log files when I get home.

**Comment by Ste1io** [comment]
Sounds good thanks. If you could include your `launch.ini` file, and `JRPC.ini` (if you have that one; note that it's a `.ini` file not the `.xex` one) along with the log that would be very helpful.

**Comment by Electric1447** [comment]
That's even wierder, using the debug version crashes the xbox and shuts it down.
Anyway heres the filles (i dont have jrpc.ini).
[log.zip](https://github.com/StelioKontosXBL/AuroraCrashPatcher/files/6445709/log.zip)

**Comment by jimbob4000** [comment]
I've experienced the same issue unfortunately

**Comment by svensvond** [comment]
Same here, if you activate this plugin original xbox games wont load.

**Comment by Ste1io** [comment]
If playing original games, open disc tray when you boot up to prevent the patch from loading without going through the hassle of modifying plugins each time.

I've since provided an official fix to the crash to Aurora, which has since been merged into their stable branch and is scheduled for release as an official hotfix update, however. So as soon as that update comes through you can safely remove this patch from your plugins. AuroraCrashPatcher will still be necessary if you use FSD.

**Comment by svensvond** [comment]
@StelioKontosXBL 
Without an actual connected DVD drive i might not be able to open any disc tray :)
There are still planned releases for aurora or any other active development?

**Comment by Ste1io** [comment]
See my reply 20 minutes ago. My fixes to the actual Aurora codebase have been implemented and Aurora 0.7b.2-hotfix is ready for deployment; I can't give a timeline for when it gets pushed out, shouldn't be long though.
