### ISSUE TITLE
Aurora dev interested in fixing this properly.

### ISSUE THREAD

**Issue by GavinDarkglider** [StelioKontosXBL/AuroraCrashPatcher#7]
Hey, finally got access to the full aurora source tree, and was planning on doing some bug fixes, and possibly new features. The first thing that should be fixed though is this asset issue. Since you were able to track it down, and dns patch it, any chance you could hit me up on discord, so we can discuss what the actual issue is, would be helpful in tracking down and fixing the issue in the aurora codebase. let me know if you are interested.

**Comment by Ste1io** [comment]
Just read this, @GavinDarkglider. Dropped you a fr on Discord. Thanks for the message and your patience, as I haven't been keeping a close enough eye on this project's issues lately.
