### ISSUE TITLE
xbox classic games restarting

### ISSUE THREAD

**Issue by ZweiBR** [StelioKontosXBL/AuroraCrashPatcher#8]
Xbox 360 Slim
Matrix Glicher RGH 1.2-v2
Corona

My xbox classic games stopped working after switching to AuroraCrashPatcher.
I did a test, that's how remove the plugin back to work

greetings from Brazil

**Comment by Makein** [comment]
> Xbox 360 Slim Matrix Glicher RGH 1.2-v2 Corona
> 
> My xbox classic games stopped working after switching to AuroraCrashPatcher. I did a test, that's how remove the plugin back to work
> 
> greetings from Brazil

You need it to update db images, after you can disable it.
On last dash I don't  have this problem

**Comment by ZweiBR** [comment]
> 

I believe the idea is to always keep active instead of deactivating

**Comment by Ste1io** [comment]
> I believe the idea is to always keep active instead of deactivating

Correct; best to just leave it running in the background all the time and simply boot with no plugins (by opening the disc tray when booting) if planning to play classic games.

**Comment by ZweiBR** [comment]
> > I believe the idea is to always keep active instead of deactivating
> 
> Correct; best to just leave it running in the background all the time and simply boot with no plugins (by opening the disc tray when booting) if planning to play classic games.

Thanks for answering
do you plan to fix this error with classic xbox games?

**Comment by Ste1io** [comment]
I have no plans on updating this patch further. Aurora pushed an official hotfix update earlier today (0.7b-2), and as I am now directly involved with the Aurora development, there shouldn't be any need for a third-party patch plugin should any issues arise in the future.

As of the time of this writing, this plugin should only be necessary if you're using FSD, which has not received an official update as of yet. If only using Aurora, you can remove it from your launch plugins once Aurora is updated.

For more info or to download the update, see the official post on the Aurora newsfeed at http://phoenix.xboxunity.net/#/news.

**Comment by ZweiBR** [comment]
> 

thanks for everything
I think the time has come to switch to AURORA.
