### ISSUE TITLE
Kernel build 17511 detected...you really should update

### ISSUE THREAD

**Issue by FreedomLabsIO** [StelioKontosXBL/AuroraCrashPatcher#9]
After adding the patch to my Aurora's launch.ini file, when I start the dash these messages appear on the log. Is it fine or should I update my kernel (is it updateable?)?

Also, I'm trying to run a RGHed version of Worms Collection on my Jasper XBOX360, I copy the Worms folder from my USB thumb drive to the HDD, but it keeps crashing and rebooting my console when I try to run it. I thought this patch could help with this matter but it still crashes.
Any ideas how can I fix this ? Thanks !

```
      9007: Kernel build 17511 detected...you really should update
      8631: Kernel build 17511 detected...you really should update
      7914: Kernel build 17511 detected...you really should update

```

**Comment by Ste1io** [comment]
launch.ini is unrelated to Aurora; all RGH consoles need that, regardless if you're using Aurora or not.

If you have updated Aurora, you don't need to use my patch at this point; it's only needed for FSD at this point

 The log messages are fairly self-explanatory. Current dash is 17559. Whether you update your dash is up to you, really, though.

**Comment by FreedomLabsIO** [comment]
> launch.ini is unrelated to Aurora; all RGH consoles need that, regardless if you're using Aurora or not.
> 
> If you have updated Aurora, you don't need to use my patch at this point; it's only needed for FSD at this point
> 
> The log messages are fairly self-explanatory. Current dash is 17559. Whether you update your dash is up to you, really, though.

Ok, thanks!
